# Generated by Django 6.0.1 on 2026-01-18 16:21

import emp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='Emp_id',
            field=models.CharField(default=emp.models.generate_emp_id, editable=False, max_length=20, unique=True),
        ),
    ]
